// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_REGISTRATION_DONE = 'CLEAR_REGISTRATION_DONE';

// Subject
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const GET_SUBJECT = 'GET_SUBJECT';
export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const SUBJECTS_ERROR = 'SUBJECTS_ERROR';
export const SUBJECT_ERROR = 'SUBJECT_ERROR';
export const CREATE_ERROR = 'CREATE_ERROR';
export const CLEAR_SUBJECTS = 'CLEAR_SUBJECTS';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const DELETE_ERROR = 'DELETE_ERROR';

// Course
export const CREATE_COURSE = 'CREATE_COURSE';
export const GET_COURSES = 'GET_COURSES';
export const COURSES_ERROR = 'COURSES_ERROR';
export const CLEAR_COURSES = 'CLEAR_COURSES';
export const GET_COURSE = 'GET_COURSE';
export const COURSE_ERROR = 'COURSE_ERROR';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';

// Download
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const DOWNLOAD_ERROR = 'DOWNLOAD_ERROR';

// Academic Batch
export const CREATE_ACADEMIC_BATCH = 'CREATE_ACADEMIC_BATCH';
export const GET_ACADEMIC_BATCHES = 'GET_ACADEMIC_BATCHES';
export const CLEAR_ACADEMIC_BATCHES = 'CLEAR_ACADEMIC_BATCHES';
export const ACADEMIC_BATCHES_ERROR = 'ACADEMIC_BATCHES_ERROR';
export const GET_ACADEMIC_BATCH = 'GET_ACADEMIC_BATCH';
export const ACADEMIC_BATCH_ERROR = 'ACADEMIC_BATCH_ERROR';
export const CREATE_FILE = 'CREATE_FILE';
export const CREATE_FILE_ERROR = 'CREATE_FILE_ERROR';
export const UPDATE_ACADEMIC_BATCH = 'UPDATE_ACADEMIC_BATCH';
export const DELETE_ACADEMIC_BATCH = 'DELETE_ACADEMIC_BATCH';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const RESET_ALERT = 'RESET_ALERT';

// Loading
export const SET_LOADING = 'SET_LOADING';
export const RESET_LOADING = 'RESET_LOADING';

// Notification
export const INIT_NOTIFICATION = 'INIT_NOTIFICATION';
export const INIT_NOTIFICATION_ERROR = 'INIT_NOTIFICATION_ERROR';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const RECONNECT_NOTIFICATION = 'RECONNECT_NOTIFICATION';
export const RECONNECT_ERROR = 'RECONNECT_ERROR';

// Meeting
export const CREATE_MEETING = 'CREATE_MEETING';
export const CLEAR_MEETINGS = 'CLEAR_MEETINGS';
export const GET_MEETINGS = 'GET_MEETINGS';
export const MEETINGS_ERROR = 'MEETINGS_ERROR';
export const GET_MEETING = 'GET_MEETING';
export const MEETING_ERROR = 'MEETING_ERROR';
export const UPDATE_MEETING = 'UPDATE_MEETING';
export const DELETE_MEETING = 'DELETE_MEETING';

// Crud Info
export const GET_CRUD_RECORDS = 'GET_CRUD_RECORDS';
export const CRUD_RECORDS_ERROR = 'CRUD_RECORDS_ERROR';
export const CLEAR_CRUD_RECORDS = 'CLEAR_CRUD_RECORDS';

// Storage
export const GET_STORAGE_INFO = 'GET_STORAGE_INFO';
export const STORAGE_INFO_ERROR = 'STORAGE_INFO_ERROR';

// User
export const GET_LOGGED_USERS = 'GET_LOGGED_USERS';
export const LOGGED_USERS_ERROR = 'LOGGED_USERS_ERROR';
export const CLEAR_USERS = 'CLEAR_USERS';
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';
export const GET_USER = 'GET_USER';
export const USER_ERROR = 'USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';

// Config
export const INIT_CONFIG = 'INIT_CONFIG';
export const INIT_CONFIG_ERROR = 'INIT_CONFIG_ERROR';
export const UPDATE_CONFIG = 'UPDATE_CONFIG';

// Account Requests
export const GET_ACCOUNT_REQUESTS = 'GET_ACCOUNT_REQUESTS';
export const ACCOUNT_REQUESTS_ERROR = 'ACCOUNT_REQUESTS_ERROR';
export const UPDATE_ACCOUNT_REQUEST = 'UPDATE_ACCOUNT_REQUEST';
